import {User} from "./Interface"
export const AdminData:User[]= [
    {
      name: 'Amit Sharma',
      email: 'amit.sharma@example.com',
      phone: '9876543210',
      designation: 'Admin',
      status: 'active',
      userId: '1',
    },
    {
      name: 'Priya Singh',
      email: 'priya.singh@example.com',
      phone: '8765432109',
      designation: 'Editor',
      status: 'inactive',
      userId: '2',
    },
    {
      name: 'Rahul Verma',
      email: 'rahul.verma@example.com',
      phone: '7654321098',
      designation: 'Viewer',
      status: 'active',
      userId: '3',
    },
    {
      name: 'Sneha Patil',
      email: 'sneha.patil@example.com',
      phone: '6543210987',
      designation: 'Editor',
      status: 'active',
      userId: '4',
    },
    {
      name: 'Vikas Rao',
      email: 'vikas.rao@example.com',
      phone: '5432109876',
      designation: 'Admin',
      status: 'inactive',
      userId: '5',
    },
    {
      name: 'Neha Gupta',
      email: 'neha.gupta@example.com',
      phone: '4321098765',
      designation: 'Viewer',
      status: 'active',
      userId: '6',
    },
    {
      name: 'Arjun Mehta',
      email: 'arjun.mehta@example.com',
      phone: '3210987654',
      designation: 'Editor',
      status: 'inactive',
      userId: '7',
    },
    {
      name: 'Sana Khan',
      email: 'sana.khan@example.com',
      phone: '2109876543',
      designation: 'Admin',
      status: 'active',
      userId: '8',
    },
    {
      name: 'Ravi Kumar',
      email: 'ravi.kumar@example.com',
      phone: '1098765432',
      designation: 'Viewer',
      status: 'inactive',
      userId: '9',
    },
    {
      name: 'Anjali Das',
      email: 'anjali.das@example.com',
      phone: '0987654321',
      designation: 'Editor',
      status: 'active',
      userId: '10',
    },
  ];
